/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package caviewer;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingWorker;

/**
 *
 * @author Paul
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        this.jRadioButton1.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Show in viewer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Two symbols");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Three symbols");

        jLabel3.setText("Word:");

        jLabel4.setText("Automaton:");

        jLabel5.setText("To:");

        jLabel6.setText("From:");

        jButton3.setText("Range Run");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Run 002001");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(jLabel2)
                                    .addComponent(jRadioButton2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5))
                                    .addComponent(jButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 23, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean checkTwoSymbolWord(String word) {
        for (int i = 0; i < word.length(); i++) {
            if (word.charAt(i) != '0' && word.charAt(i) != '1') {
                return false;
            }
        }
        return true;
    }

    private boolean checkTwoSymbolRule(long ruleNumber) {
        final long maxNumOfTwoSymbolAutomata = 256; // 2 ^ 8
        if (!(ruleNumber >= 0 && ruleNumber < maxNumOfTwoSymbolAutomata)) {
            return false;
        }
        return true;
    }

    private boolean checkThreeSymbolWord(String word) {
        for (int i = 0; i < word.length(); i++) {
            if (word.charAt(i) != '0' && word.charAt(i) != '1' && word.charAt(i) != '2') {
                return false;
            }
        }
        return true;
    }

    private boolean checkThreeSymbolRule(long automatonNumber) {
        final long maxNumOfThreeSymbolAutomata = 7625597484987L; // 3 ^ 27
        if (!(automatonNumber >= 0 && automatonNumber < maxNumOfThreeSymbolAutomata)) {
            return false;
        }
        return true;
    }

    private void showPic(long automatonNumber) {
        this.jLabel2.setText("");

        final int GRID_WIDTH = 2000;
        final int GRID_HEIGHT = 500;

        String word = this.jTextField1.getText();

        if (word.length() > GRID_WIDTH) {
            this.jLabel2.setText("Error: input word too long");
            return;
        }

        int base = 0;

        byte[][] grid = new byte[GRID_HEIGHT][GRID_WIDTH];
        BufferedImage image = new BufferedImage(GRID_WIDTH / 2, GRID_HEIGHT, BufferedImage.TYPE_INT_ARGB);
        CA automaton = null;

        if (this.jRadioButton1.isSelected() && checkTwoSymbolWord(word) && checkTwoSymbolRule(automatonNumber)) {
            automaton = new TwoSymbolAutomaton(automatonNumber);
            base = 2;
        } else if (this.jRadioButton2.isSelected() && checkThreeSymbolWord(word) && checkThreeSymbolRule(automatonNumber)) {
            automaton = new ThreeSymbolAutomaton(automatonNumber);
            base = 3;
        } else {
            this.jLabel2.setText("Error: bad word/automaton number or no radio button enabled");
            return;
        }

        // rule label
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < base * base * base; ++i) {
            String lhs = "";
            int lhsInt = i;
            lhs += (lhsInt % base);
            lhsInt /= base;
            lhs = "" + (lhsInt % base) + lhs;
            lhsInt /= base;
            lhs = "" + (lhsInt % base) + lhs;
            lhs += " -> ";
            lhs += automaton.getRhs(i);
            sb.append(lhs).append("<br>");
        }

        this.jLabel7.setText("<html>" + sb.toString() + "</html>");

        int offset = GRID_WIDTH / 2 - word.length() / 2;

        for (char ch : word.toCharArray()) {
            grid[0][offset++] = (byte) (ch - '0');
        }

        for (int i = 1; i < GRID_HEIGHT; i++) {
            for (int j = 0; j < GRID_WIDTH; j++) {
                int left = 0, middle = 0, right = 0;
                if (j > 0) {
                    left = grid[i - 1][j - 1];
                }
                middle = grid[i - 1][j];
                if (j < GRID_WIDTH - 1) {
                    right = grid[i - 1][j + 1];
                }
                int rule = left * base * base + middle * base + right;
                grid[i][j] = automaton.getRhs(rule);
            }
        }
        offset = GRID_WIDTH / 4 + 1;
        for (int i = 0; i < image.getHeight(); i++) {
            for (int j = 0; j < image.getWidth(); j++) {
                assert grid[i][j + offset] == 0 || grid[i][j + offset] == 1 || grid[i][j + offset] == 2;
                switch (grid[i][j + offset]) {
                    case 0:
                        image.setRGB(j, i, Color.WHITE.getRGB());
                        break;
                    case 1:
                        image.setRGB(j, i, Color.BLACK.getRGB());
                        break;
                    case 2:
                        image.setRGB(j, i, Color.ORANGE.getRGB());
                        break;
                }
            }
        }

        // update image
        this.jLabel1.setIcon(new ImageIcon(image));
        this.jLabel1.repaint();
        this.jLabel1.revalidate();

        // save image
        try {
            File f = new File(System.getProperty("user.dir") + "\\" + picName);
            ImageIO.write(image, "png", f);
        } catch (Exception e) {
            this.jLabel2.setText("Error: pic wasn't saved");
        }
        this.jLabel2.setText(Long.toString(automatonNumber));
    }

    // RUN BUTTON
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            long automatonNumber = Long.parseLong(this.jTextField2.getText());
            showPic(automatonNumber);
        } catch (Exception e) {
            this.jLabel2.setText("Error: couldn't parse automaton number");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // SHOW IN VIEWER BUTTON
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            File f = new File(System.getProperty("user.dir") + "\\" + picName);
            Desktop dt = Desktop.getDesktop();
            dt.open(f);
        } catch (Exception e) {
            this.jLabel2.setText("Error: couldn't open image");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private RangeRunWorker rangeRun = null;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            if (this.jButton3.getText().equals("Range Run")) {
                this.jButton3.setText("Stop");
                long from = Long.parseLong(this.jTextField3.getText());
                long to = Long.parseLong(this.jTextField4.getText());
                rangeRun = new RangeRunWorker(from, to);
                rangeRun.execute();
            } else if (this.jButton3.getText().equals("Stop")) {
                this.jButton3.setText("Range Run");
                rangeRun.cancel(true);
                rangeRun = null;
            }
        } catch (Exception e) {
            this.jLabel2.setText("Error: bad range input");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private final String picName = "temppic.png";

    class RangeRunWorker extends SwingWorker<Void, Void> {

        private final long from, to;

        public RangeRunWorker(long from, long to) {
            this.from = from;
            this.to = to;
        }

        @Override
        protected Void doInBackground() throws Exception {
            for (long i = from; i <= to; i++) {
                showPic(i);
                Thread.sleep(1000);
            }
            return null;
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}

class TwoSymbolAutomaton implements CA {

    private final byte[] rhs = new byte[8];

    public TwoSymbolAutomaton(long number) {
        for (int i = 0; i < 8; i++) {
            rhs[i] = (byte) (number % 2);
            number /= 2;
        }
    }

    @Override
    public byte getRhs(int ptr) {
        return rhs[ptr];
    }
}

class ThreeSymbolAutomaton implements CA {

    private final byte[] rhs = new byte[27];

    public ThreeSymbolAutomaton(long number) {
        for (int i = 0; i < 27; i++) {
            rhs[i] = (byte) (number % 3);
            number /= 3;
        }
    }

    @Override
    public byte getRhs(int ptr) {
        return rhs[ptr];
    }
}

interface CA {

    byte getRhs(int ptr);
}